import { ISduiRpcHandler, SduiRpcContext } from '../sdui_rpc_handler';
import { logger, HBP_LOG_TAG } from '../../lib/governor_logger';
import { JbcTranslator } from '../../ai/jbc/jbc_translator';
import { encode } from '@msgpack/msgpack';

export class ChatHandler implements ISduiRpcHandler {
  async handle(ctx: SduiRpcContext): Promise<any> {
    const params = ctx.params;
    const socket = ctx.socket;
    const rawPayload = ctx.rawPayload;

    const entryId = params.entry_id as string;
    const entryTitle = params.entry_title as string ?? 'Untitled';
    const blocks = params.blocks as any[] ?? [];
    const prompt = params.prompt as string;
    const history = params.history as any[] ?? [];

    logger.info('sdui_orchestrator', `shua.diary.chat [MOCK]: Handling prompt (${prompt.length} chars)`, { tags: HBP_LOG_TAG.SDUI | HBP_LOG_TAG.AI });
    const rawBytecode = prompt.toLowerCase().includes('checklist')
      ? "I:top|checklist|- [ ] Walk the dog\\n- [ ] Do the laundry\\n- [ ] Read 10 pages of a book"
      : prompt.toLowerCase().includes('exercise')
      ? "I:top|heading_2|JBC Exercise Plan\nI:top|markdown|Today we focus on high-intensity interval training. Make sure to stay hydrated."
      : "I:top|heading_2|JBC Copilot Section\nI:top|markdown|This content was generated by your JBC Copilot. Keep writing to build your goals!";

    // Unescape escaped newlines so translation compiles it correctly if it contains \\n
    const unescapedBytecode = rawBytecode.replace(/\\n/g, '\n');
    const parsed = JbcTranslator.parse(unescapedBytecode, blocks);
    const summaryText = JbcTranslator.translate(unescapedBytecode, blocks);

    const plan = {
      intent: parsed.intent,
      rawBytecode: unescapedBytecode,
      mutations: parsed.mutations,
      mutationsSummary: summaryText
    };

    const explanationText = prompt.toLowerCase().includes('checklist')
      ? "Sure! Let's insert a checklist block with three daily tasks right at the top of your journal."
      : prompt.toLowerCase().includes('exercise')
      ? "I have analyzed your request and compiled an exercise plan. I'm inserting a new Heading block at the top, followed by a detailed markdown introduction to HIIT."
      : "Hello! I am your JBC Copilot. I have parsed your journal state and decided to insert a new heading and markdown block at the top of your journal.";

    // Stream explanation text chunks to simulate typing
    const words = explanationText.split(' ');
    for (let i = 0; i < words.length; i++) {
      const chunk = words[i] + (i === words.length - 1 ? '' : ' ');
      const chunkPayload = {
        0: params.conversation_id || entryId,
        1: chunk,
        2: false,
        3: 'josh-chat'
      };
      socket.emit(`stream_chunk_${rawPayload.transaction_id || entryId}`, encode(chunkPayload));
      await new Promise(resolve => setTimeout(resolve, 30)); // 30ms simulation delay
    }

    const finalPayload = {
      0: params.conversation_id || entryId,
      1: '',
      2: true,
      3: 'josh-chat'
    };
    socket.emit(`stream_chunk_${rawPayload.transaction_id || entryId}`, encode(finalPayload));

    // Send the final JbcPlanResult via rpc_response
    const responsePayload = {
      0: 0, // OK status
      1: plan, // JbcPlanResult
      3: rawPayload.transaction_id
    };
    socket.emit('rpc_response', encode(responsePayload));
    return plan;
  }
}
