"""
base.py — Abstract base class for all HBP v2 language generators.

Each generator subclass implements:
  - `language_name`  property  (str)
  - `file_extension` property  (str)
  - `generate(schema)`         returns dict[filename, content]

The base class provides shared type-mapping helpers.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Optional

from tools.sync_contracts.parser import HbpProtocol, HbpEnum, HbpStruct, StructField


class BaseGenerator(ABC):

    # Subclasses must set these
    language_name:  str = ""
    file_extension: str = ""

    # ---- type mapping (override per language) ----

    # Map HBP canonical type → language type.
    # Subclasses override this dict.
    TYPE_MAP: dict[str, str] = {}

    def map_type(self, hbp_type: str, schema: HbpProtocol) -> str:
        """
        Convert an HBP canonical type string to the target language type.

        Handles:
          - Scalar types via TYPE_MAP
          - Optional scalars (e.g. "str?") → language nullable
          - Struct references (e.g. "ModuleEntry")
          - Array references (e.g. "ModuleEntry[]")
          - Optional arrays (e.g. "ModuleEntry[]?") if ever needed
        """
        optional = hbp_type.endswith("?")
        base = hbp_type.rstrip("?")
        is_array = base.endswith("[]")
        element = base.rstrip("[]") if is_array else base

        # Resolve element type
        if element in self.TYPE_MAP:
            resolved = self.TYPE_MAP[element]
        elif element in schema.enum_names():
            resolved = self.map_enum_ref(element)
        elif element in schema.struct_names():
            resolved = self.map_struct_ref(element)
        else:
            resolved = element  # pass-through (shouldn't happen)

        # Wrap in array syntax
        if is_array:
            resolved = self.wrap_array(resolved)

        # Wrap in optional/nullable syntax
        if optional:
            resolved = self.wrap_optional(resolved)

        return resolved

    def map_enum_ref(self, name: str) -> str:
        """How to reference an enum type. Override if different from struct."""
        return name

    def map_struct_ref(self, name: str) -> str:
        """How to reference a struct/class type."""
        return name

    def wrap_array(self, inner: str) -> str:
        """Wrap a type in an array. e.g. List<T>, Vec<T>, T[], etc."""
        return f"[{inner}]"  # override in subclasses

    def wrap_optional(self, inner: str) -> str:
        """Wrap a type in nullable/optional. Override in subclasses."""
        return f"{inner}?"

    # ---- header / footer ----

    def file_header(self, schema: HbpProtocol) -> str:
        """Boilerplate comment at top of generated files."""
        return (
            f"// AUTO-GENERATED by sync_contracts — DO NOT EDIT\n"
            f"// Source: tools/sync_contracts/schema/hbp_operations.toml\n"
            f"// HBP v{schema.version} — {schema.description}\n\n"
        )

    # ---- main entry point ----

    @abstractmethod
    def generate(self, schema: HbpProtocol) -> dict[str, str]:
        """
        Generate all files for this language.

        Returns:
            dict mapping relative output path → file content string.
            Paths are relative to the output root for this language.
        """
        ...
