"""
base.py — Abstract base class for all HBP v2 language generators.
"""

from __future__ import annotations

from abc import ABC, abstractmethod

from tools.sync_contracts.parser import HbpProtocol


class BaseGenerator(ABC):

    language_name:  str = ""
    file_extension: str = ""

    TYPE_MAP: dict[str, str] = {}

    def map_type(self, hbp_type: str, schema: HbpProtocol) -> str:
        optional = hbp_type.endswith("?")
        base = hbp_type.rstrip("?")

        # Handle map<K, V> types
        if base.startswith("map<") and base.endswith(">"):
            inner = base[4:-1]
            parts = [p.strip() for p in inner.split(",", 1)]
            k_type = self.map_type(parts[0], schema)
            v_type = self.map_type(parts[1], schema) if len(parts) > 1 else "str"
            resolved = self.wrap_map(k_type, v_type)
            if optional:
                resolved = self.wrap_optional(resolved)
            return resolved

        is_array = base.endswith("[]")
        element = base.rstrip("[]") if is_array else base

        if element in self.TYPE_MAP:
            resolved = self.TYPE_MAP[element]
        elif element in schema.enum_names():
            resolved = self.map_enum_ref(element)
        elif element in schema.struct_names():
            resolved = self.map_struct_ref(element)
        else:
            resolved = element

        if is_array:
            resolved = self.wrap_array(resolved)

        if optional:
            resolved = self.wrap_optional(resolved)

        return resolved

    def map_enum_ref(self, name: str) -> str:
        return name

    def map_struct_ref(self, name: str) -> str:
        return name

    def wrap_array(self, inner: str) -> str:
        return f"[{inner}]"

    def wrap_map(self, key_type: str, val_type: str) -> str:
        return f"Map<{key_type}, {val_type}>"

    def wrap_optional(self, inner: str) -> str:
        return f"{inner}?"

    def file_header(self, schema: HbpProtocol) -> str:
        return (
            f"// AUTO-GENERATED by sync_contracts — DO NOT EDIT\n"
            f"// Source: _architecture/contracts/hbp/schema/*.toml\n"
            f"// HBP v{schema.version} — {schema.description}\n\n"
        )

    @abstractmethod
    def generate(self, schema: HbpProtocol) -> dict[str, str]:
        ...
