"""
dart_gen.py — Generates Dart HBP v2 contract files.

Output files (relative to output.dart root):
  hbp_enums.dart       ← all enums as Dart enum + int value extensions
  hbp_models.dart      ← all structs as Dart freezed-style data classes
  hbp_ops.dart         ← operation string constants + typed request builders
"""

from __future__ import annotations

from tools.sync_contracts.parser import HbpProtocol, HbpEnum, HbpStruct
from tools.sync_contracts.generators.base import BaseGenerator


class DartGenerator(BaseGenerator):
    language_name  = "dart"
    file_extension = ".dart"

    TYPE_MAP = {
        "u8":   "int",
        "u32":  "int",
        "u64":  "int",
        "f32":  "double",
        "bool": "bool",
        "str":  "String",
    }

    def wrap_array(self, inner: str) -> str:
        return f"List<{inner}>"

    def wrap_optional(self, inner: str) -> str:
        return f"{inner}?"

    def map_enum_ref(self, name: str) -> str:
        return name

    def map_struct_ref(self, name: str) -> str:
        return name

    def file_header(self, schema: HbpProtocol) -> str:
        return (
            "// AUTO-GENERATED by sync_contracts — DO NOT EDIT\n"
            "// Source: tools/sync_contracts/schema/hbp_operations.toml\n"
            f"// HBP v{schema.version} — {schema.description}\n\n"
            "// ignore_for_file: always_specify_types\n\n"
        )

    # ------------------------------------------------------------------ #
    def generate(self, schema: HbpProtocol) -> dict[str, str]:
        return {
            "hbp_enums.dart":  self._gen_enums(schema),
            "hbp_models.dart": self._gen_models(schema),
            "hbp_ops.dart":    self._gen_ops(schema),
        }

    # ---- enums ---- #
    def _gen_enums(self, schema: HbpProtocol) -> str:
        lines = [self.file_header(schema)]
        for en in schema.enums:
            if en.description:
                lines.append(f"/// {en.description}")
            lines.append(f"enum {en.name} {{")
            for v in en.variants:
                if v.value is not None:
                    lines.append(f"  {_camel(v.name)}({v.value}),")
                else:
                    lines.append(f"  {_camel(v.name)},")
            if en.variants and en.variants[0].value is not None:
                # integer-coded enum — add value field + const constructor
                lines.append("")
                lines.append("  const {name}(this.value);".format(name=en.name))
                lines.append("  final int value;")
                lines.append("")
                # fromInt factory
                lines.append(f"  static {en.name} fromInt(int v) {{")
                lines.append(f"    return {en.name}.values.firstWhere((e) => e.value == v,")
                lines.append(f"        orElse: () => throw ArgumentError('Unknown {en.name}: $v'));")
                lines.append("  }")
            lines.append("}\n")
        return "\n".join(lines)

    # ---- models ---- #
    def _gen_models(self, schema: HbpProtocol) -> str:
        lines = [self.file_header(schema)]
        lines.append("import 'hbp_enums.dart';\n")
        for st in schema.structs:
            if st.description:
                lines.append(f"/// {st.description}")
            lines.append(f"class {st.name} {{")
            # fields
            for f in st.fields:
                dart_type = self.map_type(f.type, schema)
                if f.description:
                    lines.append(f"  /// {f.description}")
                lines.append(f"  final {dart_type} {_camel(f.name)};")
            lines.append("")
            # constructor
            params = ", ".join(
                f"required this.{_camel(f.name)}" for f in st.fields
            )
            lines.append(f"  const {st.name}({{{params}}});")
            lines.append("")
            # fromMap
            lines.append(f"  factory {st.name}.fromMap(Map<String, dynamic> m) {{")
            lines.append(f"    return {st.name}(")
            for f in st.fields:
                dart_type = self.map_type(f.type, schema)
                key = f.name
                raw_base = f.type.rstrip("?[]?")
                is_array = "[]" in f.type
                optional = f.type.endswith("?") and "[]" not in f.type
                if raw_base in schema.struct_names():
                    if is_array:
                        lines.append(
                            f"      {_camel(key)}: (m['{key}'] as List).map("
                            f"(e) => {raw_base}.fromMap(e as Map<String, dynamic>)).toList(),"
                        )
                    elif optional:
                        lines.append(
                            f"      {_camel(key)}: m['{key}'] != null "
                            f"? {raw_base}.fromMap(m['{key}'] as Map<String, dynamic>) : null,"
                        )
                    else:
                        lines.append(
                            f"      {_camel(key)}: {raw_base}.fromMap(m['{key}'] as Map<String, dynamic>),"
                        )
                elif raw_base in schema.enum_names():
                    lines.append(f"      {_camel(key)}: {raw_base}.fromInt(m['{key}'] as int),")
                else:
                    cast = dart_type.rstrip("?")
                    if optional:
                        lines.append(f"      {_camel(key)}: m['{key}'] as {cast}?,")
                    else:
                        lines.append(f"      {_camel(key)}: m['{key}'] as {cast},")
            lines.append("    );")
            lines.append("  }")
            lines.append("")
            # toMap
            lines.append("  Map<String, dynamic> toMap() => {")
            for f in st.fields:
                raw_base = f.type.rstrip("?[]?")
                is_array = "[]" in f.type
                if raw_base in schema.struct_names():
                    if is_array:
                        lines.append(
                            f"    '{f.name}': {_camel(f.name)}.map((e) => e.toMap()).toList(),"
                        )
                    else:
                        lines.append(f"    '{f.name}': {_camel(f.name)}?.toMap(),")
                elif raw_base in schema.enum_names():
                    v = en.variants[0] if (en := next((e for e in schema.enums if e.name == raw_base), None)) else None
                    if v and v.value is not None:
                        lines.append(f"    '{f.name}': {_camel(f.name)}.value,")
                    else:
                        lines.append(f"    '{f.name}': {_camel(f.name)}.name,")
                else:
                    lines.append(f"    '{f.name}': {_camel(f.name)},")
            lines.append("  };\n")
            lines.append("}\n")
        return "\n".join(lines)

    # ---- ops ---- #
    def _gen_ops(self, schema: HbpProtocol) -> str:
        lines = [self.file_header(schema)]
        lines.append("/// HBP v2 operation key constants.")
        lines.append("abstract final class HbpOps {")
        for op in schema.operations:
            if op.description:
                lines.append(f"  /// {op.description}")
            lines.append(f"  static const String {_snake(op.const_name)} = '{op.op_key}';")
        lines.append("}")
        lines.append("")
        # Module namespace constants
        lines.append("/// HBP v2 module namespace constants.")
        lines.append("abstract final class HbpModules {")
        for mod in schema.unique_modules():
            const = mod.replace('.', '_').upper()
            lines.append(f"  static const String {const} = '{mod}';")
        lines.append("}")
        return "\n".join(lines)


# ---- helpers ---- #

def _camel(name: str) -> str:
    """snake_case or dotted → lowerCamelCase."""
    parts = name.replace('.', '_').split('_')
    return parts[0] + ''.join(p.capitalize() for p in parts[1:])


def _snake(name: str) -> str:
    """SCREAMING_SNAKE → lower_snake_case."""
    return name.lower()
