"""
go_gen.py — Generates Go HBP v2 contract files.

Output files (relative to output.go root):
  hbp_enums.go   ← typed int/string consts
  hbp_models.go  ← structs with msgpack struct tags
  hbp_ops.go     ← operation key constants
"""

from __future__ import annotations

from tools.sync_contracts.parser import HbpProtocol, HbpEnum, HbpStruct
from tools.sync_contracts.generators.base import BaseGenerator

PACKAGE = "hbp"


class GoGenerator(BaseGenerator):
    language_name  = "go"
    file_extension = ".go"

    TYPE_MAP = {
        "u8":   "uint8",
        "u32":  "uint32",
        "u64":  "uint64",
        "f32":  "float32",
        "bool": "bool",
        "str":  "string",
    }

    def wrap_array(self, inner: str) -> str:
        return f"[]{inner}"

    def wrap_optional(self, inner: str) -> str:
        # Go uses pointers for optional scalar types
        if inner.startswith("[]") or inner[0].isupper():
            return f"*{inner}"
        return f"*{inner}"

    def file_header(self, schema: HbpProtocol) -> str:
        return (
            "// AUTO-GENERATED by sync_contracts — DO NOT EDIT\n"
            "// Source: tools/sync_contracts/schema/hbp_operations.toml\n"
            f"// HBP v{schema.version} — {schema.description}\n\n"
            f"package {PACKAGE}\n\n"
        )

    # ------------------------------------------------------------------ #
    def generate(self, schema: HbpProtocol) -> dict[str, str]:
        return {
            "hbp_enums.go":  self._gen_enums(schema),
            "hbp_models.go": self._gen_models(schema),
            "hbp_ops.go":    self._gen_ops(schema),
        }

    # ---- enums ---- #
    def _gen_enums(self, schema: HbpProtocol) -> str:
        lines = [self.file_header(schema)]
        for en in schema.enums:
            has_values = en.variants and en.variants[0].value is not None
            go_type = "int" if has_values else "string"
            if en.description:
                lines.append(f"// {en.description}")
            lines.append(f"type {en.name} {go_type}")
            lines.append("")
            lines.append("const (")
            for v in en.variants:
                const_name = f"{en.name}{v.name}"
                if has_values:
                    lines.append(f"\t{const_name} {en.name} = {v.value}")
                else:
                    lines.append(f'\t{const_name} {en.name} = "{_snake(v.name)}"')
            lines.append(")\n")
        return "\n".join(lines)

    # ---- models ---- #
    def _gen_models(self, schema: HbpProtocol) -> str:
        lines = [self.file_header(schema)]
        for st in schema.structs:
            if st.description:
                lines.append(f"// {st.description}")
            lines.append(f"type {st.name} struct {{")
            for f in st.fields:
                go_type = self.map_type(f.type, schema)
                go_name = _pascal(f.name)
                tag = f'msgpack:"{f.name}"'
                if f.description:
                    lines.append(f"\t// {f.description}")
                lines.append(f"\t{go_name} {go_type} `{tag}`")
            lines.append("}\n")
        return "\n".join(lines)

    # ---- ops ---- #
    def _gen_ops(self, schema: HbpProtocol) -> str:
        lines = [self.file_header(schema)]
        lines.append("// HBP v2 operation key constants.")
        lines.append("const (")
        for op in schema.operations:
            if op.description:
                lines.append(f"\t// {op.description}")
            lines.append(f'\t{_pascal(op.const_name)} = "{op.op_key}"')
        lines.append(")")
        lines.append("")
        lines.append("// HBP v2 module namespace constants.")
        lines.append("const (")
        for mod in schema.unique_modules():
            const = _pascal(mod.replace('.', '_'))
            lines.append(f'\t{const} = "{mod}"')
        lines.append(")")
        return "\n".join(lines)


def _snake(name: str) -> str:
    return name.replace('.', '_').lower()


def _pascal(name: str) -> str:
    parts = name.replace('.', '_').split('_')
    return ''.join(p.capitalize() for p in parts)
