"""
markdown.py — Auto-generates _architecture/contracts/hbp/API_REFERENCE.md
"""

from pathlib import Path
from tools.sync_contracts.parser import HbpProtocol

OUT_PATH = Path(__file__).parent.parent.parent.parent / "_architecture" / "contracts" / "hbp" / "API_REFERENCE.md"


def generate(proto: HbpProtocol) -> dict[Path, str]:
    lines = []
    lines.append("# HBP v2 — Master API & Operations Reference")
    lines.append("")
    lines.append(f"> **Auto-Generated by `sync_contracts`** | Protocol Version: `{proto.version}` | Port: `{proto.port}`")
    lines.append("")
    lines.append("## Overview")
    lines.append(proto.description or "Single-source-of-truth master API reference auto-generated from modular `.toml` schemas.")
    lines.append("")

    # --- Enums ---
    lines.append("## 1. Enums")
    lines.append("")
    for e in proto.enums:
        lines.append(f"### `{e.name}`")
        lines.append(e.description or "No description provided.")
        lines.append("")
        lines.append("| Variant | Integer Code |")
        lines.append("| :--- | :--- |")
        for v in e.variants:
            val_str = f"`{v.value}`" if v.value is not None else "*(auto)*"
            lines.append(f"| `{v.name}` | {val_str} |")
        lines.append("")

    # --- Structs ---
    lines.append("## 2. DTO Structs")
    lines.append("")
    for s in proto.structs:
        lines.append(f"### `{s.name}`")
        lines.append(s.description or "No description provided.")
        lines.append("")
        lines.append("| Index | Field Name | Type | Description | Notes |")
        lines.append("| :--- | :--- | :--- | :--- | :--- |")
        for f in s.fields:
            dep = f"⚠️ **Deprecated**: {f.deprecation_reason}" if f.deprecated else ""
            lines.append(f"| `{f.index}` | `{f.name}` | `{f.type}` | {f.description} | {dep} |")
        lines.append("")

    # --- Operations ---
    lines.append("## 3. Operations Registry")
    lines.append("")
    for mod in proto.unique_modules():
        lines.append(f"### Module: `{mod}`")
        lines.append("")
        lines.append("| Operation | Type | Auth Required | Request Payload | Response / Event Payload | Description |")
        lines.append("| :--- | :--- | :--- | :--- | :--- | :--- |")
        for op in proto.operations_for(mod):
            req = f"`{op.request_struct}`" if op.request_struct else "*(none)*"
            resp = f"`{op.response_struct}`" if op.response_struct else (f"`{op.event_struct}`" if op.event_struct else "*(none)*")
            auth = "✅" if op.requires_auth else "❌"
            lines.append(f"| `{op.op_key}` | `{op.op_type.upper()}` | {auth} | {req} | {resp} | {op.description} |")
        lines.append("")

    content = "\n".join(lines)
    return {OUT_PATH: content}
