"""
python_gen.py — Generates Python HBP v2 contract files.

Output files (relative to output.python root):
  hbp_enums.py   ← IntEnum / StrEnum classes
  hbp_models.py  ← dataclasses with from_dict / to_dict helpers
  hbp_ops.py     ← operation key string constants
"""

from __future__ import annotations

from tools.sync_contracts.parser import HbpProtocol, HbpEnum, HbpStruct
from tools.sync_contracts.generators.base import BaseGenerator


class PythonGenerator(BaseGenerator):
    language_name  = "python"
    file_extension = ".py"

    TYPE_MAP = {
        "u8":        "int",
        "u16":       "int",
        "u32":       "int",
        "u64":       "int",
        "f32":       "float",
        "bool":      "bool",
        "str":       "str",
        "timestamp": "int",
        "uuid":      "str",
    }

    def wrap_array(self, inner: str) -> str:
        return f"list[{inner}]"

    def wrap_map(self, key_type: str, val_type: str) -> str:
        return f"dict[{key_type}, {val_type}]"

    def wrap_optional(self, inner: str) -> str:
        return f"Optional[{inner}]"

    def file_header(self, schema: HbpProtocol) -> str:
        return (
            "# AUTO-GENERATED by sync_contracts — DO NOT EDIT\n"
            "# Source: tools/sync_contracts/schema/hbp_operations.toml\n"
            f"# HBP v{schema.version} — {schema.description}\n\n"
            "from __future__ import annotations\n\n"
        )

    # ------------------------------------------------------------------ #
    def generate(self, schema: HbpProtocol) -> dict[str, str]:
        return {
            "hbp_enums.py":  self._gen_enums(schema),
            "hbp_models.py": self._gen_models(schema),
            "hbp_ops.py":    self._gen_ops(schema),
            "__init__.py":   self._gen_init(),
        }

    # ---- enums ---- #
    def _gen_enums(self, schema: HbpProtocol) -> str:
        lines = [self.file_header(schema)]
        lines.append("from enum import IntEnum, StrEnum\n")
        for en in schema.enums:
            has_values = en.variants and en.variants[0].value is not None
            base = "IntEnum" if has_values else "StrEnum"
            if en.description:
                lines.append(f"# {en.description}")
            lines.append(f"class {en.name}({base}):")
            for v in en.variants:
                if has_values:
                    lines.append(f"    {_upper(v.name)} = {v.value}")
                else:
                    lines.append(f"    {_upper(v.name)} = '{_snake(v.name)}'")
            lines.append("")
        return "\n".join(lines)

    # ---- models ---- #
    def _gen_models(self, schema: HbpProtocol) -> str:
        lines = [self.file_header(schema)]
        lines.append("from dataclasses import dataclass, field")
        lines.append("from typing import Optional, Any")
        lines.append("from .hbp_enums import *\n")

        for st in schema.structs:
            if st.description:
                lines.append(f"# {st.description}")
            lines.append("@dataclass")
            lines.append(f"class {st.name}:")
            for f in st.fields:
                py_type = self.map_type(f.type, schema)
                default = " = None" if f.type.endswith("?") else ""
                if "list[" in py_type:
                    # lists need field(default_factory=list)
                    default = " = field(default_factory=list)"
                if f.description:
                    lines.append(f"    # {f.description}")
                lines.append(f"    {_snake(f.name)}: {py_type}{default}")
            lines.append("")
            # from_dict
            lines.append(f"    @classmethod")
            lines.append(f"    def from_dict(cls, d: dict[str, Any]) -> '{st.name}':")
            args = []
            for f in st.fields:
                raw_base = f.type.rstrip("?[]?")
                is_array = "[]" in f.type
                optional = f.type.endswith("?") and not is_array
                key = f.name
                if raw_base in schema.struct_names():
                    if is_array:
                        args.append(f"            {_snake(key)}=[{raw_base}.from_dict(e) for e in (d.get('{key}') or [])]")
                    elif optional:
                        args.append(f"            {_snake(key)}={raw_base}.from_dict(d['{key}']) if d.get('{key}') is not None else None")
                    else:
                        args.append(f"            {_snake(key)}={raw_base}.from_dict(d['{key}'])")
                elif raw_base in schema.enum_names():
                    enum_cls = raw_base
                    args.append(f"            {_snake(key)}={enum_cls}(d['{key}'])")
                else:
                    args.append(f"            {_snake(key)}=d.get('{key}')" if optional else f"            {_snake(key)}=d['{key}']")
            lines.append(f"        return cls(")
            lines.extend(args)
            lines.append("        )")
            lines.append("")
            # to_dict
            lines.append("    def to_dict(self) -> dict[str, Any]:")
            lines.append("        return {")
            for f in st.fields:
                raw_base = f.type.rstrip("?[]?")
                is_array = "[]" in f.type
                attr = _snake(f.name)
                if raw_base in schema.struct_names():
                    if is_array:
                        lines.append(f"            '{f.name}': [e.to_dict() for e in self.{attr}],")
                    else:
                        lines.append(f"            '{f.name}': self.{attr}.to_dict() if self.{attr} is not None else None,")
                elif raw_base in schema.enum_names():
                    lines.append(f"            '{f.name}': self.{attr}.value,")
                else:
                    lines.append(f"            '{f.name}': self.{attr},")
            lines.append("        }")
            lines.append("")

        return "\n".join(lines)

    # ---- ops ---- #
    def _gen_ops(self, schema: HbpProtocol) -> str:
        lines = [self.file_header(schema)]
        lines.append("# HBP v2 operation key constants")
        lines.append("class HbpOps:")
        for op in schema.operations:
            if op.description:
                lines.append(f"    # {op.description}")
            lines.append(f"    {op.const_name}: str = '{op.op_key}'")
        lines.append("")
        lines.append("# HBP v2 module namespace constants")
        lines.append("class HbpModules:")
        for mod in schema.unique_modules():
            const = mod.replace('.', '_').upper()
            lines.append(f"    {const}: str = '{mod}'")
        lines.append("")
        return "\n".join(lines)

    # ---- __init__ ---- #
    def _gen_init(self) -> str:
        return (
            "# AUTO-GENERATED by sync_contracts — DO NOT EDIT\n\n"
            "from .hbp_enums import *\n"
            "from .hbp_models import *\n"
            "from .hbp_ops import HbpOps, HbpModules\n"
        )


def _snake(name: str) -> str:
    return name.replace('.', '_').lower()


def _upper(name: str) -> str:
    return name.replace('.', '_').upper()
