"""
rust_gen.py — Generates Rust HBP v2 contract files.
"""

from __future__ import annotations

from tools.sync_contracts.parser import HbpProtocol
from tools.sync_contracts.generators.base import BaseGenerator


class RustGenerator(BaseGenerator):
    language_name  = "rust"
    file_extension = ".rs"

    TYPE_MAP = {
        "u8":        "u8",
        "u16":       "u16",
        "u32":       "u32",
        "u64":       "u64",
        "f32":       "f32",
        "bool":      "bool",
        "str":       "String",
        "timestamp": "u64",
        "uuid":      "String",
    }

    def wrap_array(self, inner: str) -> str:
        return f"Vec<{inner}>"

    def wrap_map(self, key_type: str, val_type: str) -> str:
        return f"std::collections::HashMap<{key_type}, {val_type}>"

    def wrap_optional(self, inner: str) -> str:
        return f"Option<{inner}>"

    def file_header(self, schema: HbpProtocol) -> str:
        return (
            "// AUTO-GENERATED by sync_contracts — DO NOT EDIT\n"
            "// Source: _architecture/contracts/hbp/schema/*.toml\n"
            f"// HBP v{schema.version} — {schema.description}\n\n"
            "#![allow(dead_code, non_snake_case)]\n\n"
        )

    # ------------------------------------------------------------------ #
    def generate(self, schema: HbpProtocol) -> dict[str, str]:
        return {
            "hbp_enums.rs":  self._gen_enums(schema),
            "hbp_models.rs": self._gen_models(schema),
            "hbp_ops.rs":    self._gen_ops(schema),
            "mod.rs":        self._gen_mod(),
        }

    # ---- enums ---- #
    def _gen_enums(self, schema: HbpProtocol) -> str:
        lines = [self.file_header(schema)]
        lines.append("use serde::{Deserialize, Serialize};\n")
        for en in schema.enums:
            if en.description:
                lines.append(f"/// {en.description}")
            has_values = en.variants and en.variants[0].value is not None
            if has_values:
                lines.append("#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]")
                lines.append("#[serde(rename_all = \"snake_case\")]")
                lines.append(f"pub enum {en.name} {{")
                for v in en.variants:
                    lines.append(f"    {v.name} = {v.value},")
            else:
                lines.append("#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]")
                lines.append("#[serde(rename_all = \"snake_case\")]")
                lines.append(f"pub enum {en.name} {{")
                for v in en.variants:
                    lines.append(f"    {v.name},")
            lines.append("}\n")
        return "\n".join(lines)

    # ---- models ---- #
    def _gen_models(self, schema: HbpProtocol) -> str:
        lines = [self.file_header(schema)]
        lines.append("use serde::{Deserialize, Serialize};\n")
        lines.append("use super::hbp_enums::*;\n")
        for st in schema.structs:
            if st.description:
                lines.append(f"/// {st.description}")
            lines.append("#[derive(Debug, Clone, Serialize, Deserialize)]")
            lines.append(f"pub struct {st.name} {{")
            for f in st.fields:
                rust_type = self.map_type(f.type, schema)
                if f.description:
                    lines.append(f"    /// Index {f.index}: {f.description}")
                else:
                    lines.append(f"    /// Index {f.index}")
                if f.is_optional:
                    lines.append("    #[serde(default)]")
                lines.append(f"    pub {_snake(f.name)}: {rust_type},")
            lines.append("}\n")
        return "\n".join(lines)

    # ---- ops ---- #
    def _gen_ops(self, schema: HbpProtocol) -> str:
        lines = [self.file_header(schema)]
        lines.append("/// HBP v2 operation key constants.")
        lines.append("pub mod ops {")
        for op in schema.operations:
            if op.description:
                lines.append(f"    /// {op.description}")
            lines.append(f"    pub const {op.const_name}: &str = \"{op.op_key}\";")
        lines.append("}")
        lines.append("")
        lines.append("/// HBP v2 module namespace constants.")
        lines.append("pub mod modules {")
        for mod in schema.unique_modules():
            const = mod.replace('.', '_').replace('-', '_').upper()
            lines.append(f"    pub const {const}: &str = \"{mod}\";")
        lines.append("}")
        return "\n".join(lines)

    # ---- mod.rs ---- #
    def _gen_mod(self) -> str:
        return (
            "// AUTO-GENERATED by sync_contracts — DO NOT EDIT\n\n"
            "pub mod hbp_enums;\n"
            "pub mod hbp_models;\n"
            "pub mod hbp_ops;\n\n"
            "pub use hbp_enums::*;\n"
            "pub use hbp_models::*;\n"
            "pub use hbp_ops::*;\n"
        )


def _snake(name: str) -> str:
    """Convert dotted or mixed name to snake_case."""
    return name.replace('.', '_').lower()
