"""
typescript_gen.py — Generates TypeScript HBP v2 contract files.

Output files (relative to output.typescript root):
  hbpEnums.ts   ← enums as const objects + TypeScript union types
  hbpModels.ts  ← interfaces for all structs
  hbpOps.ts     ← operation key constants as a const object
"""

from __future__ import annotations

from tools.sync_contracts.parser import HbpProtocol, HbpEnum, HbpStruct
from tools.sync_contracts.generators.base import BaseGenerator


class TypeScriptGenerator(BaseGenerator):
    language_name  = "typescript"
    file_extension = ".ts"

    TYPE_MAP = {
        "u8":        "number",
        "u16":       "number",
        "u32":       "number",
        "u64":       "number",
        "f32":       "number",
        "bool":      "boolean",
        "str":       "string",
        "timestamp": "number",
        "uuid":      "string",
    }

    def wrap_array(self, inner: str) -> str:
        return f"{inner}[]"

    def wrap_map(self, key_type: str, val_type: str) -> str:
        return f"Record<{key_type}, {val_type}>"

    def wrap_optional(self, inner: str) -> str:
        return f"{inner} | null"

    def file_header(self, schema: HbpProtocol) -> str:
        return (
            "// AUTO-GENERATED by sync_contracts — DO NOT EDIT\n"
            "// Source: tools/sync_contracts/schema/hbp_operations.toml\n"
            f"// HBP v{schema.version} — {schema.description}\n\n"
        )

    # ------------------------------------------------------------------ #
    def generate(self, schema: HbpProtocol) -> dict[str, str]:
        return {
            "hbpEnums.ts":  self._gen_enums(schema),
            "hbpModels.ts": self._gen_models(schema),
            "hbpOps.ts":    self._gen_ops(schema),
        }

    # ---- enums ---- #
    def _gen_enums(self, schema: HbpProtocol) -> str:
        lines = [self.file_header(schema)]
        for en in schema.enums:
            has_values = en.variants and en.variants[0].value is not None
            if en.description:
                lines.append(f"/** {en.description} */")
            lines.append(f"export const {en.name} = {{")
            for v in en.variants:
                if has_values:
                    lines.append(f"  {v.name}: {v.value},")
                else:
                    lines.append(f"  {v.name}: '{_snake(v.name)}',")
            lines.append("} as const;\n")
            # Derive union type
            value_union = " | ".join(
                str(v.value) if has_values else f"'{_snake(v.name)}'"
                for v in en.variants
            )
            lines.append(f"export type {en.name} = {value_union};\n")
        return "\n".join(lines)

    # ---- models ---- #
    def _gen_models(self, schema: HbpProtocol) -> str:
        lines = [self.file_header(schema)]
        lines.append("import type { MessageType, ModuleState, IntentClass } from './hbpEnums';\n")
        for st in schema.structs:
            if st.description:
                lines.append(f"/** {st.description} */")
            lines.append(f"export interface {st.name} {{")
            for f in st.fields:
                ts_type = self.map_type(f.type, schema)
                optional_key = "?" if f.type.endswith("?") else ""
                # Strip the " | null" for optional fields — use ?: instead
                clean_type = ts_type.replace(" | null", "") if optional_key else ts_type
                if f.description:
                    lines.append(f"  /** {f.description} */")
                lines.append(f"  {f.name}{optional_key}: {clean_type};")
            lines.append("}\n")
        return "\n".join(lines)

    # ---- ops ---- #
    def _gen_ops(self, schema: HbpProtocol) -> str:
        lines = [self.file_header(schema)]
        lines.append("/** HBP v2 operation key constants */")
        lines.append("export const HbpOps = {")
        for op in schema.operations:
            if op.description:
                lines.append(f"  /** {op.description} */")
            lines.append(f"  {_camel(op.const_name)}: '{op.op_key}',")
        lines.append("} as const;\n")
        lines.append("export type HbpOp = typeof HbpOps[keyof typeof HbpOps];\n")

        lines.append("/** HBP v2 module namespace constants */")
        lines.append("export const HbpModules = {")
        for mod in schema.unique_modules():
            const = _camel(mod.replace('.', '_').upper())
            lines.append(f"  {const}: '{mod}',")
        lines.append("} as const;\n")
        return "\n".join(lines)


def _snake(name: str) -> str:
    return name.replace('.', '_').lower()


def _camel(name: str) -> str:
    parts = name.replace('.', '_').split('_')
    return parts[0].lower() + ''.join(p.capitalize() for p in parts[1:])
