// AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
// Generated by tools/sync_contracts.py on 2026-07-08 11:27:35 UTC
// Source: schemas/communication_contracts.json
// To update: modify the source schema and re-run sync_contracts.py

// ignore_for_file: constant_identifier_names

import 'package:flutter/material.dart';

/// HBP frame message type constants (Byte 3 of the 12-byte header).
abstract final class HbpMessageType {
  static const int HANDSHAKE = 0; // 0x00
  static const int REQUEST = 1; // 0x01
  static const int RESPONSE = 2; // 0x02
  static const int ERROR = 3; // 0x03
  static const int TELEMETRY = 4; // 0x04
  static const int EVOLUTION = 5; // 0x05
  static const int PING = 6; // 0x06
  static const int PONG = 7; // 0x07
  static const int STREAM_CHUNK = 8; // 0x08
  static const int STREAM_END = 9; // 0x09
  static const int BINARY_PIPELINE = 10; // 0x0A
  static const int BROADCAST = 11; // 0x0B
  static const int CANCEL = 12; // 0x0C
  static const int FLOW_CONTROL = 13; // 0x0D
  static const int BATCH_REQUEST = 14; // 0x0E
  static const int BATCH_RESPONSE = 15; // 0x0F
  static const int REKEY = 16; // 0x10
  static const int STATE_SYNC = 17; // 0x11
  static const int LOG = 18; // 0x12
}

/// HBP error category constants (Byte 0 of the 0x03 Error payload).
abstract final class HbpErrorCategory {
  static const int TRANSPORT = 1; // 0x01
  static const int AUTH_SECURITY = 2; // 0x02
  static const int RPC_ROUTING = 3; // 0x03
  static const int DATABASE = 4; // 0x04
  static const int EVOLUTION_SANDBOX = 5; // 0x05
  static const int RESOURCE_EXHAUSTION = 6; // 0x06
}

/// Integer RPC method IDs (Key `0` of 0x01 REQUEST payload).
abstract final class HbpRpcMethod {
  static const int CORE_CHAT_SEND_MESSAGE = 10;
  static const int CORE_CHAT_GET_HISTORY = 11;
  static const int CORE_CHAT_NEW_CONVERSATION = 12;
  static const int CORE_CHAT_DELETE_CONVERSATION = 13;
  static const int CORE_CHAT_SET_MODE = 14;
  static const int CORE_MEMORY_GET_EPISODIC = 20;
  static const int CORE_MEMORY_HARD_DELETE = 21;
  static const int CORE_MEMORY_GET_IDENTITY_MATRIX = 22;
  static const int CORE_MEMORY_UPDATE_IDENTITY = 23;
  static const int CORE_MEMORY_GET_CITATIONS = 24;
  static const int CORE_MEMORY_SEARCH_SEMANTIC = 25;
  static const int CORE_TASKS_LIST = 30;
  static const int CORE_TASKS_CREATE = 31;
  static const int CORE_TASKS_UPDATE = 32;
  static const int CORE_TASKS_DELETE = 33;
  static const int CORE_TASKS_COMPLETE = 34;
  static const int CORE_REMINDERS_LIST = 40;
  static const int CORE_REMINDERS_CREATE = 41;
  static const int CORE_REMINDERS_DELETE = 42;
  static const int CORE_LEARN_LIST_DECKS = 50;
  static const int CORE_LEARN_CREATE_DECK = 51;
  static const int CORE_LEARN_GET_DUE_CARDS = 52;
  static const int CORE_LEARN_SUBMIT_REVIEW = 53;
  static const int CORE_LEARN_GENERATE_CARDS = 54;
  static const int CORE_PARTNER_GET_PROFILE = 60;
  static const int CORE_PARTNER_UPDATE_PROFILE = 61;
  static const int CORE_PARTNER_GET_MILESTONES = 62;
  static const int CORE_PARTNER_LOG_DATE_OUTCOME = 63;
  static const int SHUA_DIARY_LOG_ENTRY = 101;
  static const int SHUA_DIARY_GET_BLOCKS = 102;
  static const int SHUA_DIARY_GET_CALENDAR = 103;
  static const int SHUA_DIARY_SEMANTIC_SEARCH = 104;
  static const int SHUA_DIARY_GET_INSIGHTS = 105;
  static const int SHUA_DIARY_DELETE_ENTRY = 106;
  static const int SHUA_DIARY_ELEVATE_TO_GLOBAL = 107;
  static const int SHUA_DIARY_GET_MOOD_TIMELINE = 108;
  static const int SHUA_DIARY_SAVE_BLOCK = 109;
  static const int SHUA_DIARY_REORDER_BLOCK = 110;
  static const int SHUA_DIARY_DELETE_BLOCK = 111;
  static const int SHUA_DIARY_CREATE_BLOCK = 112;
  static const int SHUA_DIARY_CREATE_ENTRY = 113;
  static const int SHUA_DIARY_SET_PRIVATE = 114;
  static const int SHUA_DIARY_GENERATE_FROM_NOTES = 115;
  static const int SHUA_DIARY_CHAT = 116;
  static const int SHUA_DIARY_ANALYZE_ENTRY = 117;
  static const int SHUA_DIARY_GENERATE_SUMMARY = 118;
  static const int SHUA_DIARY_SAVE_AI_CONFIG = 119;
  static const int SHUA_DIARY_SEARCH = 120;
  static const int SHUA_DIARY_GET_MONTHLY_SYNTHESIS = 121;
  static const int SHUA_DIARY_SAVE_TITLE = 122;
  static const int SHUA_CRYPTO_GET_PRICE = 201;
  static const int SHUA_CRYPTO_GET_PORTFOLIO = 202;
  static const int SHUA_CRYPTO_ADD_ASSET = 203;
  static const int SHUA_CRYPTO_LOG_TRADE = 204;
  static const int SHUA_CRYPTO_SET_ALERT = 205;
  static const int SHUA_CRYPTO_GET_ALERTS = 206;
  static const int SHUA_CRYPTO_GET_TRADE_JOURNAL = 207;
  static const int SHUA_CRYPTO_GET_WATCHLIST = 208;
  static const int SHUA_GYM_START_SESSION = 301;
  static const int SHUA_GYM_END_SESSION = 302;
  static const int SHUA_GYM_GET_LOGS = 303;
  static const int SHUA_GYM_GET_METRICS = 304;
  static const int SHUA_TRADING_GET_STATUS = 401;
  static const int SHUA_TRADING_GET_PAPER_PORTFOLIO = 402;
  static const int SHUA_TRADING_TRIGGER_TRADE = 403;
  static const int SHUA_TRADING_APPROVE_ORDER = 404;
  static const int SHUA_TRADING_REJECT_ORDER = 405;
  static const int SHUA_TRADING_SET_MODE = 406;
  static const int SHUA_TRADING_GET_HISTORY = 407;
  static const int SHUA_TRADING_GET_STRATEGIES = 408;
  static const int SHUA_TRADING_DEPLOY_STRATEGY = 409;
  static const int SHUA_RESUME_GET_MATRIX = 501;
  static const int SHUA_RESUME_UPDATE_MATRIX = 502;
  static const int SHUA_RESUME_COMPILE_PDF = 503;
  static const int SHUA_RESUME_GET_TEMPLATES = 504;
  static const int SHUA_RESUME_LIST_COMPILED = 505;
  static const int SHUA_RESUME_ADD_WORK = 506;
  static const int SHUA_RESUME_UPDATE_WORK = 507;
  static const int SHUA_RESUME_DELETE_WORK = 508;
  static const int SHUA_RESUME_ADD_EDUCATION = 509;
  static const int SHUA_RESUME_UPDATE_EDUCATION = 510;
  static const int SHUA_RESUME_DELETE_EDUCATION = 511;
  static const int SHUA_RESUME_ADD_PROJECT = 512;
  static const int SHUA_RESUME_UPDATE_PROJECT = 513;
  static const int SHUA_RESUME_DELETE_PROJECT = 514;
  static const int SHUA_RESUME_ADD_SKILL = 515;
  static const int SHUA_RESUME_DELETE_SKILL = 516;
  static const int SHUA_RESUME_UPDATE_SKILL = 517;
  static const int SHUA_RESUME_ADD_CERTIFICATE = 518;
  static const int SHUA_RESUME_UPDATE_CERTIFICATE = 519;
  static const int SHUA_RESUME_DELETE_CERTIFICATE = 520;
  static const int SHUA_RESUME_ADD_AWARD = 521;
  static const int SHUA_RESUME_UPDATE_AWARD = 522;
  static const int SHUA_RESUME_DELETE_AWARD = 523;
  static const int SHUA_MEMORY_LANE_GET_HYPERSPACE = 601;
  static const int SHUA_MEMORY_LANE_GET_CONSTELLATION = 602;
  static const int SHUA_MEMORY_LANE_GET_MOOD_AGG = 603;
  static const int SHUA_MEMORY_LANE_GET_TRUST_BREAKDOWN = 604;
  static const int SHUA_MEMORY_LANE_GET_ON_THIS_DAY = 605;
  static const int SHUA_MEMORY_LANE_GET_CITATIONS_TOP = 606;
  static const int SHUA_MEMORY_LANE_GET_DRIFT_RADAR = 607;
  static const int SYSTEM_HEALTH = 700;
  static const int SYSTEM_GET_TELEMETRY = 701;
  static const int SYSTEM_GET_MODULE_REGISTRY = 702;
  static const int SYSTEM_GET_CONTAINER_STATES = 703;
  static const int SYSTEM_GET_WORKFLOW_LOGS = 704;
  static const int SYSTEM_GET_ACTIVITY_LOGS = 705;
  static const int SYSTEM_SAVE_CONFIG = 706;
  static const int SYSTEM_AUTH_LOGIN = 710;
  static const int SYSTEM_AUTH_LOGOUT = 711;
  static const int SYSTEM_AUTH_REFRESH_TOKEN = 712;
  static const int SYSTEM_DEVICE_REGISTER = 720;
  static const int SYSTEM_DEVICE_GET_REGISTRY = 721;
  static const int SYSTEM_NOTIFICATIONS_GET_QUEUE = 730;
  static const int SYSTEM_NOTIFICATIONS_MARK_READ = 731;
  static const int SYSTEM_LOGS_INGEST = 740;
  static const int SYSTEM_LOGS_QUERY = 741;
  static const int SYSTEM_LOGS_STREAM_SSE = 742;
  static const int SYSTEM_LOGS_GET_STATS = 743;
  static const int SYSTEM_LOGS_CLEAR_MODULE = 744;
  static const int VISUALIZER_GET_GRAPH = 750;
  static const int VISUALIZER_EXPORT_SDG = 751;
  static const int VISUALIZER_SCAN_MODULE = 752;
  static const int VISUALIZER_GET_BLAST_RADIUS = 753;
  static const int VISUALIZER_GET_GIT_DIFF_CONTEXT = 754;
  static const int VISUALIZER_GET_SYMBOL_INFO = 755;
  static const int EVOLUTION_GET_PROPOSALS = 801;
  static const int EVOLUTION_APPROVE_PROPOSAL = 802;
  static const int EVOLUTION_REJECT_PROPOSAL = 803;
  static const int EVOLUTION_GET_SNAPSHOTS = 804;
  static const int EVOLUTION_GET_STRUCTURE = 805;
  static const int INTERNAL_LLM_COMPLETION = 900;
  static const int INTERNAL_LLM_EMBED = 901;
  static const int INTERNAL_LLM_CLASSIFY_INTENT = 902;
  static const int INTERNAL_N8N_TRIGGER_WORKFLOW = 910;

  /// Zero-maintenance O(1) lookup: RPC integer ID → wire method name string.
  /// Auto-generated from communication_contracts.json — do NOT edit manually.
  /// Usage: HbpRpcMethod.names[methodId] in SduiEventDispatcher.
  static const Map<int, String> names = {
    10: 'core.chat.send_message',
    11: 'core.chat.get_history',
    12: 'core.chat.new_conversation',
    13: 'core.chat.delete_conversation',
    14: 'core.chat.set_mode',
    20: 'core.memory.get_episodic',
    21: 'core.memory.hard_delete',
    22: 'core.memory.get_identity_matrix',
    23: 'core.memory.update_identity',
    24: 'core.memory.get_citations',
    25: 'core.memory.search_semantic',
    30: 'core.tasks.list',
    31: 'core.tasks.create',
    32: 'core.tasks.update',
    33: 'core.tasks.delete',
    34: 'core.tasks.complete',
    40: 'core.reminders.list',
    41: 'core.reminders.create',
    42: 'core.reminders.delete',
    50: 'core.learn.list_decks',
    51: 'core.learn.create_deck',
    52: 'core.learn.get_due_cards',
    53: 'core.learn.submit_review',
    54: 'core.learn.generate_cards',
    60: 'core.partner.get_profile',
    61: 'core.partner.update_profile',
    62: 'core.partner.get_milestones',
    63: 'core.partner.log_date_outcome',
    101: 'shua.diary.log_entry',
    102: 'shua.diary.get_blocks',
    103: 'shua.diary.get_calendar',
    104: 'shua.diary.semantic_search',
    105: 'shua.diary.get_insights',
    106: 'shua.diary.delete_entry',
    107: 'shua.diary.elevate_to_global',
    108: 'shua.diary.get_mood_timeline',
    109: 'shua.diary.save_block',
    110: 'shua.diary.reorder_block',
    111: 'shua.diary.delete_block',
    112: 'shua.diary.create_block',
    113: 'shua.diary.create_entry',
    114: 'shua.diary.set_private',
    115: 'shua.diary.generate_from_notes',
    116: 'shua.diary.chat',
    117: 'shua.diary.analyze_entry',
    118: 'shua.diary.generate_summary',
    119: 'shua.diary.save_ai_config',
    120: 'shua.diary.search',
    121: 'shua.diary.get_monthly_synthesis',
    122: 'shua.diary.save_title',
    201: 'shua.crypto.get_price',
    202: 'shua.crypto.get_portfolio',
    203: 'shua.crypto.add_asset',
    204: 'shua.crypto.log_trade',
    205: 'shua.crypto.set_alert',
    206: 'shua.crypto.get_alerts',
    207: 'shua.crypto.get_trade_journal',
    208: 'shua.crypto.get_watchlist',
    301: 'shua.gym.start_session',
    302: 'shua.gym.end_session',
    303: 'shua.gym.get_logs',
    304: 'shua.gym.get_metrics',
    401: 'shua.trading.get_status',
    402: 'shua.trading.get_paper_portfolio',
    403: 'shua.trading.trigger_trade',
    404: 'shua.trading.approve_order',
    405: 'shua.trading.reject_order',
    406: 'shua.trading.set_mode',
    407: 'shua.trading.get_history',
    408: 'shua.trading.get_strategies',
    409: 'shua.trading.deploy_strategy',
    501: 'shua.resume.get_matrix',
    502: 'shua.resume.update_matrix',
    503: 'shua.resume.compile_pdf',
    504: 'shua.resume.get_templates',
    505: 'shua.resume.list_compiled',
    506: 'shua.resume.add_work',
    507: 'shua.resume.update_work',
    508: 'shua.resume.delete_work',
    509: 'shua.resume.add_education',
    510: 'shua.resume.update_education',
    511: 'shua.resume.delete_education',
    512: 'shua.resume.add_project',
    513: 'shua.resume.update_project',
    514: 'shua.resume.delete_project',
    515: 'shua.resume.add_skill',
    516: 'shua.resume.delete_skill',
    517: 'shua.resume.update_skill',
    518: 'shua.resume.add_certificate',
    519: 'shua.resume.update_certificate',
    520: 'shua.resume.delete_certificate',
    521: 'shua.resume.add_award',
    522: 'shua.resume.update_award',
    523: 'shua.resume.delete_award',
    601: 'shua.memory_lane.get_hyperspace',
    602: 'shua.memory_lane.get_constellation',
    603: 'shua.memory_lane.get_mood_agg',
    604: 'shua.memory_lane.get_trust_breakdown',
    605: 'shua.memory_lane.get_on_this_day',
    606: 'shua.memory_lane.get_citations_top',
    607: 'shua.memory_lane.get_drift_radar',
    700: 'system.health',
    701: 'system.get_telemetry',
    702: 'system.get_module_registry',
    703: 'system.get_container_states',
    704: 'system.get_workflow_logs',
    705: 'system.get_activity_logs',
    706: 'system.save_config',
    710: 'system.auth.login',
    711: 'system.auth.logout',
    712: 'system.auth.refresh_token',
    720: 'system.device.register',
    721: 'system.device.get_registry',
    730: 'system.notifications.get_queue',
    731: 'system.notifications.mark_read',
    740: 'system.logs.ingest',
    741: 'system.logs.query',
    742: 'system.logs.stream_sse',
    743: 'system.logs.get_stats',
    744: 'system.logs.clear_module',
    750: 'visualizer.get_graph',
    751: 'visualizer.export_sdg',
    752: 'visualizer.scan_module',
    753: 'visualizer.get_blast_radius',
    754: 'visualizer.get_git_diff_context',
    755: 'visualizer.get_symbol_info',
    801: 'evolution.get_proposals',
    802: 'evolution.approve_proposal',
    803: 'evolution.reject_proposal',
    804: 'evolution.get_snapshots',
    805: 'evolution.get_structure',
    900: 'internal.llm.completion',
    901: 'internal.llm.embed',
    902: 'internal.llm.classify_intent',
    910: 'internal.n8n.trigger_workflow',
  };
}

/// Integer parameter keys (inside Key `1` params map of 0x01 REQUEST).
abstract final class HbpParamKey {
  static const int TEXT = 0;
  static const int TIMESTAMP = 1;
  static const int USER_ID = 2;
  static const int CONVERSATION_ID = 3;
  static const int MESSAGE_ID = 4;
  static const int ENTRY_ID = 5;
  static const int ENTRY_TYPE = 6;
  static const int MOOD_SCORE = 7;
  static const int ENERGY_SCORE = 8;
  static const int TAGS = 9;
  static const int CONTENT = 10;
  static const int TITLE = 11;
  static const int STATUS = 12;
  static const int PRIORITY = 13;
  static const int DUE_AT = 14;
  static const int SYMBOL = 15;
  static const int EXCHANGE = 16;
  static const int QUANTITY = 17;
  static const int PRICE = 18;
  static const int SIDE = 19;
  static const int LIMIT = 20;
  static const int OFFSET = 21;
  static const int QUERY = 22;
  static const int MODE = 23;
  static const int TEMPLATE = 24;
  static const int VERSION = 25;
  static const int STRATEGY_ID = 26;
  static const int LIVE_MODE = 27;
  static const int MAX_TRADE_USD = 28;
  static const int DAILY_LOSS_LIMIT = 29;
  static const int DEVICE_UUID = 30;
  static const int PLATFORM_TYPE = 31;
  static const int TOKEN = 32;
  static const int ORCHESTRATION_MODE = 33;
  static const int ACTIVE_SPECIALISTS = 34;
  static const int THINKING_BUDGET = 35;
}

/// SDUI widget type integer IDs (Key `1` of SDUI payload).
abstract final class HbpWidget {
  static const int MARKDOWNEDITOR = 1;
  static const int CODEEDITOR = 2;
  static const int BUTTON = 3;
  static const int CHECKBOX = 4;
  static const int CHIP = 5;
  static const int CONTAINER = 6;
  static const int GRIDVIEW = 7;
  static const int LISTEDITOR = 8;
  static const int LISTVIEW = 9;
  static const int ORDINALSLIDER = 10;
  static const int SLIDER = 11;
  static const int PROGRESSBAR = 12;
  static const int RADIO = 13;
  static const int SHIMMERLOADER = 14;
  static const int TABLE = 15;
  static const int TEXTINPUT = 16;
  static const int TOGGLE = 17;
  static const int TERMINAL = 18;
  static const int HEATMAP = 19;
  static const int MAP = 20;
  static const int DRAWINGPAD = 21;
  static const int AUDIOPLAYER = 22;
  static const int VIDEOPLAYER = 23;
  static const int IMAGEVIEWER = 24;
  static const int STLVIEWER = 25;
  static const int CHART = 26;
  static const int GAUGE = 27;
  static const int TIMELINE = 28;
  static const int DOCUMENTVIEWER = 29;
  static const int CAROUSEL = 30;
  static const int HTMLVIEWER = 31;
  static const int DATEPICKER = 32;
  static const int TIMEPICKER = 33;
  static const int DIVIDER = 34;
  static const int SPACER = 35;
  static const int EXPANSIONTILE = 36;
  static const int WRAP = 37;
  static const int DROPDOWN = 38;
  static const int MODULECARD = 39;
  static const int HYPERGRAPH = 40;
}

/// SDUI core node structure integer keys.
abstract final class HbpNode {
  static const int TYPE_ID = 0;
  static const int NODE_ID = 1;
  static const int CHILDREN = 2;
  static const int BEHAVIORS = 3;
  static const int CONTENT = 4;
  static const int VISIBLE = 5;
  static const int ENABLED = 6;
}

/// SDUI behavior axis integer keys.
abstract final class HbpBehavior {
  static const int LAYOUT_DIRECTION = 10;
  static const int MAIN_AXIS_ALIGNMENT = 11;
  static const int CROSS_AXIS_ALIGNMENT = 12;
  static const int MAIN_AXIS_SIZE = 13;
  static const int FLEX = 14;
  static const int OVERFLOW = 15;
  static const int BACKGROUND_COLOR = 20;
  static const int BORDER_RADIUS = 21;
  static const int BORDER_WIDTH = 22;
  static const int BORDER_COLOR = 23;
  static const int SHADOW_ELEVATION = 24;
  static const int SHADOW_COLOR = 25;
  static const int CLIP_BEHAVIOR = 26;
  static const int OPACITY = 27;
  static const int PADDING = 30;
  static const int MARGIN = 31;
  static const int WIDTH = 32;
  static const int HEIGHT = 33;
  static const int MIN_WIDTH = 34;
  static const int MAX_WIDTH = 35;
  static const int MIN_HEIGHT = 36;
  static const int MAX_HEIGHT = 37;
  static const int ASPECT_RATIO = 38;
  static const int BIND_KEY = 40;
  static const int INPUT_TYPE = 41;
  static const int KEYBOARD_TYPE = 42;
  static const int OBSCURE_TEXT = 43;
  static const int MIN_VALUE = 44;
  static const int MAX_VALUE = 45;
  static const int STEP = 46;
  static const int NORMALIZE_OUTPUT = 47;
  static const int FORM_ID = 48;
  static const int VALIDATION_RULES = 49;
  static const int SCROLL_DIRECTION = 50;
  static const int CROSS_AXIS_COUNT = 51;
  static const int ITEM_EXTENT = 52;
  static const int SEPARATOR_HEIGHT = 53;
  static const int SHRINK_WRAP = 55;
  static const int LIST_STYLE = 60;
  static const int BULLET_STYLE = 61;
  static const int ACCENT_ICON = 62;
  static const int MAX_ITEMS = 63;
  static const int MIN_ITEMS = 64;
  static const int ACTION_PAYLOAD = 70;
  static const int ON_LONG_PRESS = 71;
  static const int ON_DOUBLE_TAP = 72;
  static const int ON_SWIPE = 73;
  static const int MOUNT_ANIM = 80;
  static const int EXIT_ANIM = 81;
  static const int ANIM_DURATION_MS = 82;
  static const int ANIM_CURVE = 83;
  static const int SYNC_STRATEGY = 90;
  static const int SHIMMER_TYPE = 91;
  static const int SHIMMER_ANIM_STYLE = 92;
  static const int LINE_COUNT = 93;
  static const int LAST_LINE_WIDTH_PCT = 94;
  static const int INTERACTIVE_MODE = 95;
  static const int ACCENT_COLOR_TOKEN = 96;
  static const int TEXT_COLOR_TOKEN = 97;
  static const int DISPLAY_MODE = 100;
  static const int HEADING_LEVEL = 101;
  static const int TEXT_ALIGN = 102;
  static const int TEXT_STYLE = 103;
  static const int CODE_LANGUAGE = 110;
  static const int BUTTON_VARIANT = 112;
  static const int CHIP_MODE = 113;
  static const int MAIN_AXIS_SPACING = 114;
  static const int CROSS_AXIS_SPACING = 115;
  static const int CHILD_ASPECT_RATIO = 116;
  static const int CHART_TYPE = 117;
  static const int ALLOW_ZOOM = 118;
  static const int ORDINAL_MODE = 119;
  static const int HALF_STEP = 120;
  static const int SHOW_LABEL = 121;
  static const int SLIDER_MODE = 122;
  static const int PROGRESS_MODE = 123;
  static const int GROUP_ID = 124;
  static const int MIN_ROWS = 125;
  static const int MIN_COLS = 126;
  static const int COL_WIDTH = 127;
  static const int MAX_LINES = 128;
  static const int COLUMNS = 130;
  static const int ROWS = 131;
  static const int COLOR_INTENSITY_STEPS = 132;
  static const int CELL_ASPECT_RATIO = 133;
  static const int SHOW_HEADERS = 134;
  static const int PICKER_MODE = 135;
}

/// SDUI content integer keys.
abstract final class HbpContent {
  static const int VALUE = 0;
  static const int LABEL = 1;
  static const int PLACEHOLDER = 2;
  static const int ICON_NAME = 3;
  static const int IS_LOADING = 4;
  static const int SRC = 5;
  static const int DATA = 6;
  static const int CUSTOM_EMOJIS = 7;
}

/// SDUI action type integer IDs.
abstract final class HbpActionType {
  static const int RPC_CALL = 1;
  static const int NAVIGATE = 2;
  static const int DISMISS = 3;
  static const int LAUNCH_MODULE = 4;
  static const int LAUNCH_URL = 5;
  static const int WEBHOOK_POST = 6;
  static const int REFRESH = 7;
  static const int COPY_TO_CLIPBOARD = 8;
  static const int BIOMETRIC_GATE = 9;
  static const int STATE_SYNC = 10;
  static const int SUBMIT_FORM = 11;
  static const int AI_COMMAND = 12;
}

/// Values for behavior key 100 (display_mode) on MarkdownEditor.
abstract final class HbpDisplayMode {
  static const int BODY = 0;
  static const int HEADING = 1;
  static const int QUOTE = 2;
  static const int CAPTION = 3;
  static const int CODE_INLINE = 4;
}

/// Values for behavior key 95 (interactive_mode). Universal across all stateful primitives.
abstract final class HbpInteractiveMode {
  static const int READONLY = 0;
  static const int EDITABLE = 1;
}

/// Values for behavior key 10 (layout_direction) on Container.
abstract final class HbpLayoutDir {
  static const int VERTICAL = 0;
  static const int HORIZONTAL = 1;
  static const int STACK = 2;
}

/// Values for main_axis_alignment (11) and cross_axis_alignment (12) on Container.
abstract final class HbpAlignment {
  static const int START = 0;
  static const int END = 1;
  static const int CENTER = 2;
  static const int SPACEBETWEEN = 3;
  static const int SPACEAROUND = 4;
  static const int SPACEEVENLY = 5;
  static const int STRETCH = 6;
  static const int BASELINE = 7;
}

/// Values for behavior key 15 (overflow) on Container.
abstract final class HbpOverflow {
  static const int VISIBLE = 0;
  static const int CLIP = 1;
  static const int SCROLL = 2;
}

/// Values for behavior key 26 (clip_behavior) on Container.
abstract final class HbpClipBehavior {
  static const int NONE = 0;
  static const int ANTIALIAS = 1;
  static const int HARDEDGE = 2;
}

/// Values for behavior key 41 (input_type) on TextInput.
abstract final class HbpInputType {
  static const int TEXT = 0;
  static const int NUMBER = 1;
  static const int PASSWORD = 2;
  static const int EMAIL = 3;
  static const int MULTILINE = 4;
}

/// Values for behavior key 42 (keyboard_type) on TextInput.
abstract final class HbpKeyboardType {
  static const int TEXT = 0;
  static const int NUMBER = 1;
  static const int DECIMAL = 2;
  static const int EMAIL = 3;
  static const int PHONE = 4;
  static const int MULTILINE = 5;
}

/// Values for behavior key 60 (list_style) on ListEditor.
abstract final class HbpListStyle {
  static const int TAGS = 0;
  static const int CHECKLIST = 1;
  static const int BULLETS = 2;
  static const int NUMBERS = 3;
  static const int CUSTOM = 4;
  static const int RADIO = 5;
}

/// Values for behavior key 61 (bullet_style) on ListEditor.
abstract final class HbpBulletStyle {
  static const int DOT = 0;
  static const int DASH = 1;
  static const int ASTERISK = 2;
  static const int ARROW = 3;
}

/// Values for behavior key 50 (scroll_direction) on ListView and GridView.
abstract final class HbpScrollDir {
  static const int VERTICAL = 0;
  static const int HORIZONTAL = 1;
}

/// Values for behavior key 119 (ordinal_mode) on OrdinalSlider.
abstract final class HbpOrdinalMode {
  static const int STAR_RATING = 0;
  static const int SEGMENTED_PICKER = 1;
}

/// Values for behavior key 122 (slider_mode) on Slider.
abstract final class HbpSliderMode {
  static const int SINGLE = 0;
  static const int RANGE = 1;
}

/// Values for behavior key 135 (picker_mode) on DatePicker and TimePicker.
abstract final class HbpPickerMode {
  static const int SINGLE = 0;
  static const int RANGE = 1;
}

/// Values for behavior key 123 (progress_mode) on ProgressBar. null value = indeterminate.
abstract final class HbpProgressMode {
  static const int LINEAR = 0;
  static const int CIRCULAR = 1;
  static const int RADIAL = 2;
}

/// Values for behavior key 112 (button_variant) on Button.
abstract final class HbpButtonVariant {
  static const int ELEVATED = 0;
  static const int OUTLINED = 1;
  static const int TEXT = 2;
  static const int ICON_ONLY = 3;
  static const int FILLED_TONAL = 4;
}

/// Values for behavior key 113 (chip_mode) on Chip.
abstract final class HbpChipMode {
  static const int READ_ONLY = 0;
  static const int SELECTABLE = 1;
  static const int DELETABLE = 2;
  static const int SUGGESTION = 3;
}

/// Values for behavior keys 80 (mount_anim) and 81 (exit_anim) on Container.
abstract final class HbpMountAnim {
  static const int NONE = 0;
  static const int FADE_IN = 1;
  static const int SLIDE_UP = 2;
  static const int SLIDE_DOWN = 3;
  static const int SCALE_IN = 4;
}

/// Values for behavior key 83 (anim_curve) on Container.
abstract final class HbpAnimCurve {
  static const int LINEAR = 0;
  static const int EASEIN = 1;
  static const int EASEOUT = 2;
  static const int EASEINOUT = 3;
  static const int BOUNCEOUT = 4;
}

/// Values for behavior key 90 (sync_strategy) on ListView and GridView.
abstract final class HbpSyncStrategy {
  static const int STATIC = 0;
  static const int ON_FOCUS = 1;
  static const int POLL_5S = 2;
  static const int POLL_30S = 3;
  static const int ON_DELTA = 4;
}

/// Values for behavior key 91 (shimmer_type) on ShimmerLoader and ListView.
abstract final class HbpShimmerType {
  static const int RECT = 0;
  static const int CIRCLE = 1;
  static const int PARAGRAPH = 2;
  static const int LIST_TILE = 3;
  static const int MEDIA_CARD = 4;
  static const int CHAT_BUBBLE = 5;
  static const int STAT_CARD = 6;
  static const int FEED_ROW = 7;
}

/// Values for behavior key 92 (shimmer_anim_style) on ShimmerLoader.
abstract final class HbpShimmerAnim {
  static const int FADE_PULSE = 0;
  static const int LINEAR_SWEEP = 1;
}

/// Values for behavior key 103 (text_style). Maps to Flutter TextTheme slots.
abstract final class HbpTextStyle {
  static const int DISPLAYLARGE = 0;
  static const int DISPLAYMEDIUM = 1;
  static const int DISPLAYSMALL = 2;
  static const int HEADLINELARGE = 3;
  static const int HEADLINEMEDIUM = 4;
  static const int HEADLINESMALL = 5;
  static const int TITLELARGE = 6;
  static const int TITLEMEDIUM = 7;
  static const int BODYLARGE = 8;
  static const int BODYMEDIUM = 9;
  static const int BODYSMALL = 10;
}

/// Values for behavior key 102 (text_align) on MarkdownEditor and TextInput.
abstract final class HbpTextAlign {
  static const int START = 0;
  static const int CENTER = 1;
  static const int END = 2;
  static const int JUSTIFY = 3;
}

/// Named color token indices (0-99). Values >= 0xFF000000 are raw ARGB.
abstract final class HbpColorToken {
  static const int TRANSPARENT = 0;
  static const int PRIMARY = 1;
  static const int ON_PRIMARY = 2;
  static const int PRIMARY_CONTAINER = 3;
  static const int ON_PRIMARY_CONTAINER = 4;
  static const int SECONDARY = 5;
  static const int ON_SECONDARY = 6;
  static const int SECONDARY_CONTAINER = 7;
  static const int ON_SECONDARY_CONTAINER = 8;
  static const int SURFACE = 9;
  static const int ON_SURFACE = 10;
  static const int SURFACE_CONTAINER = 11;
  static const int SURFACE_CONTAINER_HIGHEST = 12;
  static const int OUTLINE = 13;
  static const int OUTLINE_VARIANT = 14;
  static const int ERROR = 15;
  static const int ON_ERROR = 16;
  static const int ON_SURFACE_VARIANT = 17;
}

/// Values for behavior key 110 (code_language) on CodeEditor. 20 syntax rulesets.
abstract final class HbpCodeLang {
  static const int PYTHON = 1;
  static const int DART = 2;
  static const int TYPESCRIPT = 3;
  static const int JAVASCRIPT = 4;
  static const int JSON = 5;
  static const int BASH = 6;
  static const int RUST = 7;
  static const int GO = 8;
  static const int CPP = 9;
  static const int JAVA = 10;
  static const int CSHARP = 11;
  static const int SWIFT = 12;
  static const int KOTLIN = 13;
  static const int RUBY = 14;
  static const int PHP = 15;
  static const int SQL = 16;
  static const int HTML = 17;
  static const int CSS = 18;
  static const int YAML = 19;
  static const int MARKDOWN = 20;
}

/// Integer table IDs for 0x11 STATE_SYNC delta payloads.
abstract final class HbpDbTable {
  static const int USERS = 1;
  static const int CONVERSATIONS = 2;
  static const int MESSAGES = 3;
  static const int TASKS = 4;
  static const int REMINDERS = 5;
  static const int DIARY_ENTRIES = 6;
  static const int LEARN_DECKS = 7;
  static const int LEARN_CARDS = 8;
  static const int LEARN_SESSIONS = 9;
  static const int CRYPTO_ASSETS = 10;
  static const int CRYPTO_TRADES = 11;
  static const int CRYPTO_ALERTS = 12;
  static const int USER_PROFILE = 13;
  static const int USER_IDENTITY_MATRIX = 14;
  static const int PARTNER_PROFILE = 15;
  static const int PARTNER_PREFERENCES = 16;
  static const int RELATIONSHIP_MILESTONES = 17;
  static const int NOTIFICATION_QUEUE = 18;
  static const int RESUME_MATRIX = 19;
}

/// S.H.U.A. module integer IDs.
abstract final class HbpModule {
  static const int CORE_CHAT = 0;
  static const int SHUA_DIARY = 1;
  static const int SHUA_CRYPTO = 2;
  static const int SHUA_GYM_VISION = 3;
  static const int SHUA_TRADING_BOT = 4;
  static const int SHUA_RESUME = 5;
  static const int SHUA_MEMORY_LANE = 6;
  static const int SHUA_CODE_REVIEW = 7;
  static const int SHUA_EDGE_ML = 8;
  static const int SHUA_BILL_TRACKER = 9;
  static const int SHUA_GOVERNOR = 10;
  static const int CLIENT_FLUTTER = 11;
  static const int SHUA_CODE_VISUALIZER = 12;
}

/// Device platform type integer IDs.
abstract final class HbpPlatform {
  static const int ANDROID = 0;
  static const int IOS = 1;
  static const int LINUX_DESKTOP = 2;
  static const int WINDOWS_DESKTOP = 3;
  static const int WEB = 4;
}

/// LLM intent classification output integer IDs.
abstract final class HbpIntent {
  static const int CHAT = 0;
  static const int TASK = 1;
  static const int REMINDER = 2;
  static const int LEARN = 3;
  static const int JOURNAL = 4;
  static const int CRYPTO = 5;
  static const int RESEARCH = 6;
  static const int EVOLVE = 7;
  static const int MEMORY_DELETE = 8;
  static const int GYM = 9;
  static const int TRADING = 10;
  static const int RESUME = 11;
}

/// Predefined HBP logging levels as compact integers.
abstract final class HbpLogLevel {
  static const int TRACE = 1;
  static const int DEBUG = 2;
  static const int INFO = 3;
  static const int WARN = 4;
  static const int ERROR = 5;
  static const int CRITICAL = 6;
}

/// 24-bit predefined system log tag bitmask flags.
abstract final class HbpLogTag {
  static const int SYSTEM = 1;
  static const int LIFECYCLE = 2;
  static const int NETWORK = 4;
  static const int DATABASE = 8;
  static const int SDUI = 16;
  static const int PERF = 32;
  static const int SECURITY = 64;
  static const int AI = 128;
  static const int RESERVED_1 = 256;
  static const int RESERVED_2 = 512;
  static const int RESERVED_3 = 1024;
  static const int RESERVED_4 = 2048;
  static const int RESERVED_5 = 4096;
  static const int RESERVED_6 = 8192;
  static const int RESERVED_7 = 16384;
  static const int RESERVED_8 = 32768;
  static const int RESERVED_9 = 65536;
  static const int RESERVED_10 = 131072;
  static const int RESERVED_11 = 262144;
  static const int RESERVED_12 = 524288;
  static const int RESERVED_13 = 1048576;
  static const int RESERVED_14 = 2097152;
  static const int RESERVED_15 = 4194304;
  static const int RESERVED_16 = 8388608;
}

/// Helper to map HbpColorToken integer values to Material ColorScheme colors.
Color? resolveHbpColorToken(BuildContext context, int token) {
  final cs = Theme.of(context).colorScheme;
  return switch (token) {
    HbpColorToken.TRANSPARENT => Colors.transparent,
    HbpColorToken.PRIMARY => cs.primary,
    HbpColorToken.ON_PRIMARY => cs.onPrimary,
    HbpColorToken.PRIMARY_CONTAINER => cs.primaryContainer,
    HbpColorToken.ON_PRIMARY_CONTAINER => cs.onPrimaryContainer,
    HbpColorToken.SECONDARY => cs.secondary,
    HbpColorToken.ON_SECONDARY => cs.onSecondary,
    HbpColorToken.SECONDARY_CONTAINER => cs.secondaryContainer,
    HbpColorToken.ON_SECONDARY_CONTAINER => cs.onSecondaryContainer,
    HbpColorToken.SURFACE => cs.surface,
    HbpColorToken.ON_SURFACE => cs.onSurface,
    HbpColorToken.SURFACE_CONTAINER => cs.surfaceContainer,
    HbpColorToken.SURFACE_CONTAINER_HIGHEST => cs.surfaceContainerHighest,
    HbpColorToken.OUTLINE => cs.outline,
    HbpColorToken.OUTLINE_VARIANT => cs.outlineVariant,
    HbpColorToken.ERROR => cs.error,
    HbpColorToken.ON_ERROR => cs.onError,
    HbpColorToken.ON_SURFACE_VARIANT => cs.onSurfaceVariant,
    _ => null,
  };
}

