#!/usr/bin/env python3
"""
setup_overnight_agent.py — One-time setup for the horAIzon overnight agent.

Run this once before using overnight_agent.py:
  python tools/setup_overnight_agent.py

What it does:
1. Installs aider-chat via pip
2. Checks Ollama is running
3. Pulls the recommended coding model
4. Writes a .aider.conf.yml for this repo
5. Verifies the full pipeline works
"""

from __future__ import annotations

import subprocess
import sys
import shutil
from pathlib import Path

REPO_ROOT     = Path(__file__).parent.parent
RECOMMENDED   = "qwen2.5-coder:7b"
FALLBACK      = "llama3.1:8b"
SMALL         = "llama3.2:3b"   # for low VRAM / testing
OLLAMA_URL    = "http://localhost:11434"


def run(cmd: list[str], check: bool = True, **kwargs) -> subprocess.CompletedProcess:
    print(f"  $ {' '.join(cmd)}")
    return subprocess.run(cmd, check=check, **kwargs)


def detect_vram_gb() -> float | None:
    """Try to detect GPU VRAM. Returns GB or None if not detectable."""
    try:
        result = run(
            ["nvidia-smi", "--query-gpu=memory.total", "--format=csv,noheader,nounits"],
            capture_output=True, text=True, check=False
        )
        if result.returncode == 0:
            mb = int(result.stdout.strip().split("\n")[0].strip())
            return mb / 1024
    except FileNotFoundError:
        pass
    return None


def recommend_model(vram_gb: float | None) -> str:
    """Pick the best model based on detected VRAM."""
    if vram_gb is None:
        print("  [!] Could not detect VRAM. Defaulting to 7b (safe for 8GB VRAM).")
        return FALLBACK
    if vram_gb >= 12:
        print(f"  [+] {vram_gb:.0f}GB VRAM detected — recommending qwen2.5-coder:14b (Q4_K_M ~8.7GB)")
        return RECOMMENDED
    if vram_gb >= 7:
        print(f"  [+] {vram_gb:.0f}GB VRAM detected — recommending qwen2.5-coder:7b (Q4_K_M ~4.7GB)")
        return FALLBACK
    print(f"  [+] {vram_gb:.0f}GB VRAM detected — recommending qwen2.5-coder:3b (Q4_K_M ~2.0GB)")
    return SMALL


def step_install_aider() -> None:
    print("\n[1/5] Installing aider-chat...")
    try:
        run([sys.executable, "-m", "pip", "install", "--upgrade", "aider-chat"])
        print("  [OK] aider-chat installed")
    except subprocess.CalledProcessError:
        print("  [!] pip install failed. Try: pip install aider-chat")
        sys.exit(1)


def step_check_ollama() -> None:
    print("\n[2/5] Checking Ollama...")
    if not shutil.which("ollama"):
        print("  [!] Ollama not found.")
        print("      Install from: https://ollama.com/download")
        print("      After install, run: ollama serve")
        sys.exit(1)

    result = run(["ollama", "list"], capture_output=True, text=True, check=False)
    if result.returncode != 0:
        print("  [!] Ollama is not running.")
        print("      Start it: ollama serve")
        print("      (In a separate terminal, keep it running)")
        sys.exit(1)
    print("  [OK] Ollama is running")


def step_pull_model() -> str:
    print("\n[3/5] Selecting and pulling coding model...")
    vram = detect_vram_gb()
    model = recommend_model(vram)

    result = run(["ollama", "list"], capture_output=True, text=True, check=False)
    if model in result.stdout:
        print(f"  [OK] {model} already downloaded")
        return model

    print(f"  Pulling {model}... (this may take a while on first run)")
    try:
        run(["ollama", "pull", model])
        print(f"  [OK] {model} ready")
    except subprocess.CalledProcessError:
        print(f"  [!] Failed to pull {model}. Check disk space and Ollama connection.")
        sys.exit(1)

    return model


def step_write_aider_config(model: str) -> None:
    print("\n[4/5] Writing .aider.conf.yml...")
    config = f"""\
# aider configuration for horAIzon 3.0
# Auto-generated by tools/setup_overnight_agent.py
# Docs: https://aider.chat/docs/config/aider_conf.html

model: ollama/{model}

# Use repo-map to help aider understand the codebase structure
map-tokens: 2048

# Auto-commit completed work
auto-commits: true
dirty-commits: true

# Coding style
attribute-author: false
attribute-committer: false

# Don't ask for confirmation — required for unattended runs
yes: false    # set to true in overnight_agent.py via --yes flag

# Cache model responses (saves tokens on repeated runs)
cache-prompts: true
cache-keepalive-pings: 5

# Logging
# Log file per session — overnight_agent.py sets this per task
"""
    conf_path = REPO_ROOT / ".aider.conf.yml"
    conf_path.write_text(config, encoding="utf-8")
    print(f"  [OK] Written: {conf_path}")

    # Add to .gitignore (aider creates .aider* files we don't want committed)
    gitignore = REPO_ROOT / ".gitignore"
    if gitignore.exists():
        content = gitignore.read_text(encoding="utf-8")
        lines_to_add = [
            "# aider",
            ".aider*",
            ".aider.conf.yml",
        ]
        additions = [l for l in lines_to_add if l not in content]
        if additions:
            gitignore.write_text(
                content + "\n" + "\n".join(additions) + "\n",
                encoding="utf-8"
            )
            print("  [OK] Added .aider* entries to .gitignore")


def step_smoke_test(model: str) -> None:
    print("\n[5/5] Smoke test — aider ping...")
    result = subprocess.run(
        [
            "aider",
            "--model", f"ollama/{model}",
            "--yes",
            "--message", "Reply with only the word PONG and nothing else.",
            "--no-auto-commits",
            "--exit",
        ],
        cwd=str(REPO_ROOT),
        capture_output=True,
        text=True,
        timeout=120,
        env={
            **__import__("os").environ,
            "OPENAI_API_BASE": f"{OLLAMA_URL}/v1",
            "OPENAI_API_KEY": "ollama",
        },
    )
    if "PONG" in result.stdout.upper() or result.returncode == 0:
        print("  [OK] aider + Ollama pipeline working")
    else:
        print("  [!] Smoke test inconclusive — check manually:")
        print(f"      aider --model ollama/{model} --yes --message 'say hello'")
        print(f"  stdout: {result.stdout[:500]}")
        print(f"  stderr: {result.stderr[:500]}")


def print_usage(model: str) -> None:
    print(f"""
{'='*60}
 Setup Complete!
{'='*60}

 Model ready:  {model}

 Run a single task overnight:
   python tools/overnight_agent.py TASK-003

 Run all Phase 1 tasks in order (leave running overnight):
   python tools/overnight_agent.py --all

 Dry run (preview only):
   python tools/overnight_agent.py --all --dry-run

 Logs are saved to:
   _architecture/progress/agent_logs/

 To monitor progress while it runs (new terminal):
   Get-Content _architecture/progress/agent_logs/*.log -Wait -Tail 50

 Task status legend in the MD files:
   [ ] Not started
   [/] In progress (agent is working on this)
   [x] Done

 TIP: Run as a Windows Scheduled Task for true overnight automation.
      See: tools/schedule_overnight.ps1
{'='*60}
""")


def main() -> None:
    print("""
======================================================
 horAIzon 3.0 — Overnight Agent Setup
======================================================
""")
    step_install_aider()
    step_check_ollama()
    model = step_pull_model()
    step_write_aider_config(model)
    step_smoke_test(model)
    print_usage(model)


if __name__ == "__main__":
    main()
